name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      - name: Build
        run: xcodebuild -scheme resumebuilder -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' build
      - name: Test
        run: xcodebuild test -scheme resumebuilder -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' 